### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by Gredys** [BL0CK-X/theblockchainapi-typescript-wrapper#1]
By downloading project and trying to pass `npm install` command I am getting many errors realted to lost type and other errors.

Example of first error in list:
`apis/ProjectApi.ts:70:62 - error TS4073: Parameter 'UNKNOWN_PARAMETER_NAME' of public method from exported class has or is using private name ''.

70     public async createProjectVersion(UNKNOWN_PARAMETER_NAME: , UNKNOWN_PARAMETER_NAME2: , _options?: Configuration): Promise<RequestContext> {`

Project can't be build with default setup described in readme.

**Comment by joshwolff1** [comment]
Hey! I just needed to update all the repos. I'll close this and correspond with you in Discord to figure it out!
